version: "3"

services:
  mysql-master:
        build:
          context: ./mysql-master
        environment:
          - MYSQL_USER=root
          - MYSQL_PASSWORD=root
          - MYSQL_ROOT_PASSWORD=root
        volumes:
          - $PWD/mysql-master/data:/var/lib/mysql
        ports:
          - "3307:3306"

  mysql-slave:
        build:
          context: ./mysql-slave
        environment:
          - MYSQL_USER=root
          - MYSQL_PASSWORD=root
          - MYSQL_ROOT_PASSWORD=root
        volumes:
          - $PWD/mysql-slave/data:/var/lib/mysql
        ports:
          - "3308:3306"